#!/bin/bash
set -e
#
#
#_______________________________________________
#Terminal Version of mySystemHealth
#_______________________________________________
# Name   : mySystemHealth
# Licence: GPL3 (http://www.gnu.org/licenses/gpl.html)
# Author : Efstathios Iosifidis
# WebSite: http://iosifidis.gr
# Email  : stathis-(at)-iosifidis.gr
# Date   : 08-08-2023 (first release 17-07-2023)
# Version: 1.0
# System : Fedora Linux and derivatives.
# Description:
# This script will update your system by refreshing the package list, 
# downloading and installing any available updates, and removing any outdated packages and configuration files. 
#
## Script starts here

# Here are the Variables
# DATE=$(date +%F_%T)
MYSYSTEM_VERSION="Fedora"

# Checks if the user has run the script with "sudo" or not
if [[ $EUID -ne 0 ]] ; then
    clear
    echo ""
    echo "mySystemHealth must be run as root or with sudo. Now I will just exit..." 1>&2
    echo ""
    sleep 2
    exit 1
fi

function WELCOME_SCREEN {
    echo "_________________________________________________________"
    echo "                                                       "
    echo "            mySystemHealth $MYSYSTEM_VERSION           "
    echo "            ~~~~~~~~~~~~~~~~~~~~~               	 "
    echo "                                                       "
    echo " Welcome to System Update and maintenance app.         "
    echo "                                                       "
    echo " This script will fully update your system.	 	 "
    echo "                   				         "
    echo " You can contribute to this script here:	         "
    echo " https://github.com/iosifidis/mySystemHealth	         "
    echo "                   				         "
    echo " If you find this script useful and have saved you time, "
    echo " you can make a donation to the author via PayPal.     "
    echo " The donation link is provided below.    		 "
    echo "                   				         "
    echo "           https://cutt.ly/eiosifidis                  "
    echo "                   	or			         "
    echo "           https://www.paypal.me/eiosifidis            "
    echo "_________________________________________________________"
    echo
    echo " mySystemHealth will start in 4 seconds... "

    sleep 5
}

function MAINTENANCE {
    echo
    echo
    echo "#########################"
    echo "        Started"
    echo "#########################"
    echo

    ## Updates package lists
    sudo dnf check-update;
    echo
    echo "###############################"
    echo "Finished updating package lists"
    echo "###############################"
    sleep 1

    ## Updates packages and libraries
    sudo dnf upgrade -y;
    echo
    echo "###############################################"
    echo "Finished updating packages and system libraries"
    echo "###############################################"
    sleep 1
    echo

    ## Removes unneeded packages
    sudo dnf autoremove -y;
    echo
    echo "###################################"
    echo "Finished removing unneeded packages"
    echo "###################################"
    sleep 1
    echo

    ## Removes old kernels
    sudo dnf --setopt=protected_packages= remove -y $(rpm -q kernel-core | grep -v $(uname -r));
    echo
    echo "###################################"
    echo "Finished removing old kernels"
    echo "###################################"
    sleep 1
    echo

    ## Removes unused config files
    sudo dnf remove $(dnf repoquery --installonly --latest-limit=-1 -q) -y;
    echo
    echo "#####################################"
    echo "Finished removing unused config files"
    echo "#####################################"
    sleep 1
    echo

    ## Removes package files that can no longer be downloaded
    sudo dnf clean all;
    echo
    echo "######################################"
    echo "Cleaned downloaded temporary packages"
    echo "######################################"
    echo
    sleep 1

    ## Updates Flatpak packages
    sudo flatpak update -y;
    echo
    echo "######################################"
    echo "Finished updating Flatpak packages"
    echo "######################################"
    echo
    sleep 1

    ## Removes unused Flatpak runtimes and extensions
    sudo flatpak uninstall --unused -y;
    echo
    echo "##########################################################"
    echo "Finished removing unused Flatpak runtimes and extensions"
    echo "##########################################################"
    echo
    sleep 1
    
    ## Clears Flatpak cache
    sudo rm -rf /var/tmp/flatpak-cache*;
    echo
    echo "######################################"
    echo "Finished clearing Flatpak cache"
    echo "######################################"
    echo
    sleep 1

    ## Clears cached data
    free -h && sudo sysctl -w vm.drop_caches=3 && sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && free -h;
    echo
    echo "###############################################"
    echo "Finished clearing cached data and system memory"
    echo "###############################################"
    echo
    sleep 1

    echo
    echo "#########################################"
    echo "   Thank you for using mySystemHealth    "
    echo "#########################################"
    echo

}


function GOODBYE {
    sleep 2
    echo
    echo
    echo "##################################"
    echo " All Done... Hasta la vista, baby "
    echo "##################################"
}




## If no parameter is given, just do the regular maintenance
WELCOME_SCREEN && MAINTENANCE && GOODBYE

